// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HomeView: typeof import('./src/views/HomeView.vue')['default']
    PageBuilder: typeof import('./src/views/PageBuilder.vue')['PageBuilder']
    LessonsList: typeof import('./src/components/LessonsList.vue')['LessonsList']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export { }
